[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libzip-dev zip unzip libpng-dev libjpeg-dev libfreetype6-dev"
]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "php artisan storage:link",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"